---
name: Weihao Li
date: "Dec, 2021"
qualifications: BCom(Hons), BSc
address: Clayton, Victoria, Australia
phone: +61 404 591 219
email: patrick.li@monash.edu
github: TengMCing
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
# Sys.setlocale("LC_ALL","English")
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  
# PhD
  "Doctor of Philosophy", "Department of Econometrics and Business Statistics, Monash University", "Clayton, Australia", "Mar. 2021 - Mar. 2024", "PhD research topic is Advances in Artificial Intelligence for Data Visualization: Developing Computer Vision Models to Automate Reading of Data Plots, with Application to Predictive Model Diagnostics",
  
# Honours
  "BCom (Hons) in Econometrics", "Monash University", "Clayton, Australia", "Mar. 2020 - Dec. 2020", "First Class Honours, GPA: 3.9/4.0",
  
  "BCom (Hons) in Econometrics", "Monash University", "Clayton, Australia", "Mar. 2020 - Dec. 2020", "Honours research project was to develop a spatiotemporal clustering algorithm for accurately identifing bushfire ignition locations from satellite hotspot data and a machine learning model for predicting causes of 2019-2020 Victorian bushfires.",
  
  "BCom (Hons) in Econometrics", "Monash University", "Clayton, Australia", "Mar. 2020 - Dec. 2020", "Studied units include collaborative and reproducible practices, Bayesian and frequentist econometrics and exploratory data analysis.",
  

# Bachelor of Commerce
  "BCom in Business Analytics",  "Monash University", "Clayton, Australia", "Mar. 2018 - Nov. 2019", "High Distinction, GPA: 3.5/4.0",
  
  "BCom in Business Analytics",  "Monash University", "Clayton, Australia", "Mar. 2018 - Nov. 2019", "Studied a variety of units covering different aspects of data analysis include data access, management, cleaning, visualization and modelling.",
  
  "BCom in Business Analytics",  "Monash University", "Clayton, Australia", "Mar. 2018 - Nov. 2019", "Minored in Finance enhanced my investment analysis skills in currency, equity, debt and derivatives markets.",
  

# Bachelor of Finance
  "BFin in Finance",  "Guangdong University of Finance", "Guangzhou, China", "Sep. 2015 - Jun. 2020", 'GPA: 3.4/4.0',

  "BFin in Finance",  "Guangdong University of Finance", "Guangzhou, China", "Sep. 2015 - Jun. 2020", 'Studied foundation courses in commerce and finance.') %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Awards

```{r}
tribble(
  ~ grants, ~ amount, ~ dates,
  "Monash Graduate Scholarship, Monash University", "", "2021",
  "Monash International Tuition Scholarship, Monash University", "", "2021",
  "Dean’s Honour, Business School, Monsh University", "", "2020",
  "Econometrics Honours Memorial Scholarship, Monash University", "$15,000", "2020") %>% 
  brief_entries(grants, dates, amount)
```

# Teaching experience

```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  
# PhD
  "Tutor", "ETC5521 - Exploratory Data Analysis", "Monash University", "2021 S2", NA,
  "Tutor", "ETC3250/ETC5250 - Introduction to Machine Learning", "Monash University", "2021 S1", NA,
  "Assistant Instructor", "Summer Institute in Statistics for Big Data - Module 4: Visualization of Biomedical Big Data", "University of Washington", "Jul 21 - 23, 2021", NA,
  ) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```


<!-- # Research interest -->

<!-- \footnotesize -->
<!-- \begin{itemize} -->
<!--   \item Applications of machine learning in business, finance, economic and environmental science -->
<!--   \item Computer vision and Natural Language Processing -->
<!--   \item Data visualization -->
<!--   \item Bayesian machine learning -->
<!-- \end{itemize} -->

\normalsize

# Research experience

```{r}
tribble(
  ~ name, ~ when, ~ role, ~ details,
  "Using Remote Sensing Data to Understand Fire Ignitions in Victoria during the 2019-2020 Australian Bushfire Season", "2020", "Author", "Honours degree research project, supervised by Prof Di Cook and Emily Dodwell") %>%
  brief_entries(glue::glue("\\textbf{<name>} \\newline <details>", .open = "<", .close = ">"), when, .protect = FALSE)
```

# Software development

```{r}
tribble(
  ~ com, ~ uni, ~ loc, ~ dates, ~ details,
  "spotoroo: Spatiotemporal Clustering of Satellite Hot Spot Data", "R package", "2021", "Author, Maintainer", NA) %>% 
  detailed_entries(uni, dates, com, loc, details)
```

# Data analysis projects

```{r}
tribble(
  ~ com, ~ uni, ~ loc, ~ dates, ~ details,
  "Predicting Wikipedia Daily Click Volume", "Deep Learning Project", "2019", "", "Used deep learning to predict the next year daily click volume of a Wikipedia website given the data of the previous 500 days.",
  "Predicting Wikipedia Daily Click Volume", "Deep Learning Project", "2019", "", "Tested different deep learning architectures include pure Fully Connected neural network, LSTM, GRU and 1D Convolution neural network for this time-series task.",
  "Predicting Wikipedia Daily Click Volume", "Deep Learning Project", "2019", "", "Tuned Hyperparameters using cross-validated grid-search.",
  "Predicting Wikipedia Daily Click Volume", "Deep Learning Project", "2019", "", "Prediction performance was much better than ETS and ARIMA in most of the cases.",
  "Predicting How Points End in Tennis", "InClass Kaggle Competition", "2019", "", "Used machine learning algorithms to predict outcome categories of tennis points given 3D coordinates of the ball position and 2D coordinates of the player position throughout a match.",
  "Predicting How Points End in Tennis", "InClass Kaggle Competition", "2019", "", "Applied ensemble learning to aggregate the prediction of several neural networks, XGBoost, CatBoost and Random forests models which are trained independently.",
  "Predicting How Points End in Tennis", "InClass Kaggle Competition", "2019", "", "Top 10 of the private leaderboard.",
  "Modelling And Predicting The Performance Of Portfolios Consisting of ASX200 Stocks", "Financial Econometrics Project", "2019", "", "Used ARIMA-ARCH-type models to predict the log return and volatility of portfolios given the past performance.",
  "Modelling And Predicting The Performance Of Portfolios Consisting of ASX200 Stocks", "Financial Econometrics Project", "2019", "", "Successfully constructed a hypothetical portfolio with a high Sharpe ratio and passed a 3-months review.",
  "Data Analysis Of Melbourne Airbnb Market", "Data Modelling Project", "2018", "", "Used classical regression models to explore the factors affecting Melbourne Airbnb price and rating."  ) %>% 
  detailed_entries(uni, dates, com, loc, details)
```


# Volunteer activities

```{r}
tribble(
  ~ com, ~ uni, ~ loc, ~ dates, ~ details,
  "R workshops for Beginners", "Helper", "2019", "", "A series of student ran workshops on data analysis in R.",
  "R workshops for Beginners", "Helper", "2019", "", "Workshop topics include introduction to R, Rstudio and Rmarkdown, data visualization in ggplot2, data types and import data in R, data wrangling with dplyr and handling missing data with naniar.") %>% 
  detailed_entries(uni, dates, com, loc, details)
```


<!-- # Publications -->

<!-- ```{r} -->
<!-- bibliography_entries("Weihao_Li.bib") -->
<!-- ``` -->


